module.exports = {
    username: "sakon90hd",
    token: "oauth:v3kosk5ws1wh79dop6yieuvgnx4y0e",
    channels: [
        "pepo3393live",
        "bnicot",
        "celletto91",
        "manuelitotv",
        "gracesvringhi",
        "giuseppe88",
        "godener7",
        "iracle_",
        "rinaldi00_official",
        "panetty",
        "alisprayer",
        "migliaccin",
        "copycat_",
        "cappellaio_matto",
        "soreasybrusche",
        "homyatol",
        "iamjump_",
        "howimetyourcat",
        "migliaccin",
        "bicky01",
        "pio3d",
        "caku21",
        "il_lambo",
        "lady_ally",
        "riomasterr",
        "iosonogrut",
        "doesntmatterprod",
        "alienh",
        "pendry",
        "superimen"
    ]
}
